QuanLiCuaHang/Models/LoaiSanPham.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace QuanLiCuaHang.Models
{

    [Table("dbo.LOAISANPHAM")]
    public class LoaiSanPham
    {
        [Key]
        public int MaLoaiSP { get; set; }
        public string TenLoaiSP { get; set; }
        public double? PhanTramLoiNhuan { get; set; }
        public int MaDVT { get; set; }

    }
}

QuanLiCuaHang/Areas/Manager/Controllers/LoaiSanPhamController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using QuanLiCuaHang.Models;

namespace QuanLiCuaHang.Areas.Manager.Controllers
{

    public class LoaiSanPhamController : Controller
    {
        // GET: Manager/LoaiSanPham

        public ActionResult ChiTiet(int id)
        {
            LoaiSanPhamContext loaisanphamContext = new LoaiSanPhamContext();
            LoaiSanPham loaiSanPham = loaisanphamContext.LoaiSanPham.Single(lsp => lsp.MaLoaiSP == id);
            //LoaiSanPham loaiSanPham = loaisanphamContext.LoaiSanPham.Single(lsp => lsp.MaLoaiSanPham == MaLoaiSanPham);
            return View(loaiSanPham);
        }

        public ActionResult DanhSach()
        {
            LoaiSanPhamContext loaisanphamContext = new LoaiSanPhamContext();
            List<LoaiSanPham> loaiSanPham = loaisanphamContext.LoaiSanPham.ToList();
            //LoaiSanPham loaiSanPham = loaisanphamContext.LoaiSanPham.Single(lsp => lsp.MaLoaiSanPham == MaLoaiSanPham);
            return View(loaiSanPham);
        }

        [HttpGet]
        [ActionName("Tao")]
        public ActionResult Tao_Get()
        {
            return View();
        }


        [HttpPost]
        [ActionName("Tao")]
        public ActionResult Tao_Post(LoaiSanPham loaisanpham)
        {

            //LoaiSanPham loaisanpham = new LoaiSanPham();
            //loaisanpham.TenLoaiSP = formCollection["TenLoaiSP"];
            //loaisanpham.PhanTramLoiNhuan = Int32.Parse(formCollection["PhanTramLoiNhuan"]);
            //loaisanpham.MaDVT = Int32.Parse(formCollection["MaDVT"]);

            if (ModelState.IsValid)
            {


                LoaiSanPhamContext loaiSanPhamContext = new LoaiSanPhamContext();
                loaiSanPhamContext.AddLoaiSanPham(loaisanpham);
                RedirectToAction("Danhsach");

            }
            return View();
        }

        // Hàm sửa loại sản phẩm
        [HttpGet]
        [ActionName("Sua")]
        public ActionResult Sua_Get(int id)
        {
            LoaiSanPhamContext loaiSanPhamContext = new LoaiSanPhamContext();
            LoaiSanPham loaisanpham = loaiSanPhamContext.LoaiSanPham.Single(lsp => lsp.MaLoaiSP == id);

            return View(loaisanpham);

        }

        [HttpPost]
        [ActionName("Sua")]
        public ActionResult Sua_Post(int id)
        {
            LoaiSanPhamContext loaiSanPhamContext = new LoaiSanPhamContext();
            LoaiSanPham loaisanpham = loaiSanPhamContext.LoaiSanPham.Single(x => x.MaLoaiSP == id);
            UpdateModel(loaisanpham, new string[] { "TenLoaiSP", "PhanTramLoiNhuan", "MaDVT" });
            if (ModelState.IsValid)
            {
     
                loaiSanPhamContext.SaveLoaiSanPham(loaisanpham);
                return RedirectToAction("Danhsach");
            }
            return View(loaisanpham);

        }

        // Ham xoa loai san pham
        
       
        public ActionResult Xoa(int id)
        { 
            LoaiSanPhamContext loaiSanPhamContext = new LoaiSanPhamContext();
            loaiSanPhamContext.DeleteLoaiSanPham(id);
            return RedirectToAction("Danhsach");

        }
    }
}

QuanLiCuaHang/Areas/Manager/Views/LoaiSanPham/ChiTiet.cshtml
@model QuanLiCuaHang.Models.LoaiSanPham

@{
    ViewBag.Title = "ChiTiet";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

<h2>Chi Tiết Loại Sản Phẩm</h2>
<table>
    <tr>
        <td>
            <b> Mã LSP</b>
        </td>
        <td>
            @Model.MaLoaiSP
        </td>
    </tr>
    <tr>
        <td>
            <b> Tên Loại Sản Phẩm</b>
        </td>
        <td>
            @Model.TenLoaiSP  
        </td>
    </tr>
    <tr>
        <td>
            <b> Mã DVT</b>
        </td>
        <td>
            @Model.MaDVT
           
        </td>
    </tr>
</table>

QuanLiCuaHang/Areas/Manager/Views/LoaiSanPham/DanhSach.cshtml
@model IEnumerable<QuanLiCuaHang.Models.LoaiSanPham>
@*@model IEnumerable<QuanLiCuaHang.Models.DVT>*@


@{
    ViewBag.Title = "Test";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

<style>
    .button {
        border: none;
        color: blue;
        padding: 8px 0px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 2px 0px 2px 900px;
        transition-duration: 0.4s;
        cursor: pointer;
        float: right;
    }

    .button1 {
        background-color: whitesmoke;
        color: black;
        border: 3px solid #4CAF50;
    }
</style>

<h2 style="text-align:center; color:red">Danh sách các loại sản phẩm</h2>
<form action="~/Manager/LoaiSanPham/Tao">
    <button type="submit" class="button button1">
        Thêm sản phẩm
    </button>
</form>
<table class="table" border="1">
    <tr>
        <th style="color:blue; text-align:center; font-size:20px">
            Tên loại sản phẩm
        </th>
        <th style="color:blue; text-align:center; font-size:20px">
            Phần Trăm Lợi Nhuận
            @*@Html.DisplayNameFor(model => model.PhanTramLoiNhuan)*@
        </th>
        <th style="color:blue; text-align:center; font-size:20px">
            Mã đơn vị tính
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        using (Html.BeginForm("Xoa", "LoaiSanPham", new { id = item.MaLoaiSP }))
        {
            <tr>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.TenLoaiSP)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.PhanTramLoiNhuan)
                </td>
                <td style="text-align:center">
                    @*@Html.DisplayFor(modelItem => item.TenDVT)*@
                </td>
                <td>
                    @Html.ActionLink("Sửa", "Sua", new { id = item.MaLoaiSP }) |
                    @*@Html.ActionLink("Chi Tiết", "ChiTiet", new { id = item.MaLoaiSP }) |*@
                    @*@Html.ActionLink("Xóa", "Xoa", new { id = item.MaLoaiSP })*@

                    <input type="submit" value="Xóa" onclick="return confirm ('Bạn chắc chắn muốn xóa không?'" />

                </td>
            </tr>
        }
    }

</table>

QuanLiCuaHang/Areas/Manager/Views/LoaiSanPham/Sua.cshtml
@model QuanLiCuaHang.Models.LoaiSanPham

@{
    ViewBag.Title = "Sua";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

<h2>Sua</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>LoaiSanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.MaLoaiSP)*@

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.MaLoaiSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.MaLoaiSP)
                @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenLoaiSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenLoaiSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenLoaiSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhanTramLoiNhuan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhanTramLoiNhuan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhanTramLoiNhuan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDVT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDVT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaDVT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QuanLiCuaHang/Areas/Manager/Views/LoaiSanPham/Tao.cshtml
@model QuanLiCuaHang.Models.LoaiSanPham

@{
    ViewBag.Title = "Tao";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

<h2> Tạo loại sản phẩm</h2>

@using (Html.BeginForm())
{
    <meta charset="utf-8" />

          @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="text-align:center; color:red">TẠO LOẠI SẢN PHẨM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MaLoaiSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenLoaiSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenLoaiSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenLoaiSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhanTramLoiNhuan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhanTramLoiNhuan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhanTramLoiNhuan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDVT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDVT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaDVT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mới" class="" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "DanhSach")
</div>